### ISSUE TITLE
Is this working? 

### ISSUE THREAD

**Issue by philschmid** [cargo-lambda/cargo-lambda-cdk#10]
Hello, 

I tried to use `cargo-lambda-cdk` to build a lambda function with API Gateway in front of it. But i was not successful. The build and deployment worked, but you received the following error when executing the function. I am using local builds (no docker since those fail building) on macOS with an M1
```bash
Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]
Runtime.InvalidEntrypoint
```

When comparing the created lambda function with another function I have, I found the difference that the `cargo-lambda-cdk` creates a nested structure which leads to the error. 

**working structure** 
<img width="382" alt="Bildschirmfoto 2023-03-09 um 22 35 30" src="https://user-images.githubusercontent.com/32632186/224166465-aacd2b9c-1fcd-4037-a49f-d05955c78ad2.png">

**cargo lambda structure** 
<img width="277" alt="Bildschirmfoto 2023-03-09 um 22 35 42" src="https://user-images.githubusercontent.com/32632186/224166512-89f6418a-2178-4be7-be03-dd1aa3ac6ffb.png">

**Comment by philschmid** [comment]
I managed to deploy the `example` i ll dig and find to see what the difference is and share here.

**Comment by philschmid** [comment]
Found the issue the `package-name` (second parameter) in the cdk construct `RustFunction` needs to be equivalent to the package name in the `Cargo.toml` otherwise the `cdk.out` will create a nested folder in the assethash. 
Wow...

**Comment by MinisculeGirraffe** [comment]
Literally just ran into this. Felt like I was going crazy

**Comment by hffmnn** [comment]
I just ran into this and here is what I found:

Given a Rust function with package name `rust-function` in `Cargo.toml` this deployment works:

```
new RustFunction(this, "rust-function", {
      manifestPath: path.join(__dirname, "..", "..", "rust-function")
    });
```

The next one doesn't but in a rather surprising way: bundling works, but the `bootstrap` binary is in a subpath of the generated asset folder called `rust-function`:

```
new RustFunction(this, "some-package-name", {
      manifestPath: path.join(__dirname, "..", "..", "rust-function")
    });
```

The user only "sees" the problem after deployment when calling the lambda function and getting the error mentioned above:
```
Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]
Runtime.InvalidEntrypoint
```

But: this configuration also works:

```
new RustFunction(this, "some-cdk-id-that-has-nothing-to-do-with-the-package-name", {
      binaryName: "rust-function",
      manifestPath: path.join(__dirname, "..", "..", "rust-function")
    });
```

It also has the advantage that bundling fails if the given binary name does not exist and that the second parameter can be used as usual in cdk contexts: for the construct id and not as a hidden parameter for bundling. The error with an invalid `binaryName` looks like this:
```
Error: Failed to bundle asset <project>/<some-cdk-id-that-has-nothing-to-do-with-the-package-name>/Code/Stage, bundle output is located at <some path>/cdk.out/bundling-temp-<hash>-error: Error: bash exited with status 1
```

In order to prevent other users from running into this problem the `binaryName` prop could be marked as non-optional which would be a breaking change but because this package is at version `0.0.14` I guess it would be ok? 

What do you think?

**Comment by MinisculeGirraffe** [comment]
That would be better than the existing implementation. The CDK construct name should not be directly tied to the binary name.  Tying the two together is just a foot gun.

The most preferable solution to me would be to just read the cargo.toml file and infer the binary name from the config.  That way the binaryName prop could be left optional.

**Comment by MinisculeGirraffe** [comment]
Sounds good.  I'll try and put one through tomorrow.
