### ISSUE TITLE
Expose cargo-lambda "include" option

### ISSUE THREAD

**Issue by lmammino** [cargo-lambda/cargo-lambda-cdk#58]
It would be nice if this construct exposes the `include` function that was added to `cargo-lambda` in https://github.com/cargo-lambda/cargo-lambda/pull/650

**Comment by calavera** [comment]
I think you can use build flags for that: https://github.com/cargo-lambda/cargo-lambda-cdk?tab=readme-ov-file#cargo-lambda-build-flags

But if you want a specific attribute, feel free to open a PR, it can be more useful for other people.

**Comment by lmammino** [comment]
This is awesome, I didn't realise it was so easy to pass build flags! That works for me now.

This is probably not the right place to ask, but I'll try anyway since it might be relevant for other people in the future: do you know if something similar (build flags) is supported also with SAM?

Thanks once more!

**Comment by calavera** [comment]
> do you know if something similar (build flags) is supported also with SAM?

it’s not supported in the SAM cli. I built the adapter and I don’t think it’s been touched ever since 😅 It should not be hard to implement, if you want to look into it.

I’m going to close this issue as completed, but feel free to start a discussion if you want to discuss this and other features further.
